<div style='width=100%; display:flex;flex-direction:row'><img  src=https://universidadeuropea.com/resources/media/images/universidad-europea-logo_poc9mEM.original.png width=100  style='  margin-left: auto;margin-right: auto; width: 25%; height:25%;'><img  src=https://i.ibb.co/1068C7j/EATEASER.jpg width=100 style='  margin-left: auto;margin-right: auto; width: 10%;height:25%;'></div>

<div style='margin:auto;text-align: center;font-family: "Times New Roman", Times, serif; font-weight: bold;'>PROYECTO COMUTACIONAL<br><br>EATEASER - VOZ A TEXTO</div>

<div style='width:100%; display:flex;flex-direction:row'>
    <div style='width:50%;margin-right:5cm;'>
        <p style='font-family: "Times New Roman", Times, serif; font-weight: bold;'>ESTUDIANTES</p>
<ul style='font-family: "Times New Roman", Times, serif;'>
    <li>Adilem Dobras 21911633</li><li>Roberto Echevarria 21823680</li><li>Carlos Gonzales 22067726</li><li>Juan Carlos Rondeau 21816176</li></ul> </div>

</div>

<h2 style="font-size: 19px;color:#6DA0FF;font-family:Georgia, Times, 'Times New Roman', serif;letter-spacing: 3px;font-weight: normal">1. Importamos las librerias</h2>

In [1]:
import glob
import os
import re
import requests
import pathlib
import sys

try:
    from pytube import YouTube
    from pytube import Playlist
except ModuleNotFoundError:
    !pip install pytube
try:
    import speech_recognition as sr
except ModuleNotFoundError:
    !pip install SpeechRecognition
try:
    from pydub import AudioSegment
    from pydub.silence import split_on_silence
except:
    !pip install pydub
try:
    import moviepy.editor as mp
except:
    !pip install moviepy
try:
    from bs4 import BeautifulSoup
except:
    !pip install beautifulsoup4
try:
    from nltk.stem import PorterStemmer
    from nltk.tokenize import word_tokenize
except:
    !pip install nltk  

C:\Users\thena\.conda\envs\EatEaser\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


<h2 style="font-size: 19px;color:#6DA0FF;font-family:Georgia, Times, 'Times New Roman', serif;letter-spacing: 3px;font-weight: normal">2. Inicio del programa</h2>

<h3  style='font-family: "Times New Roman", Times, serif; font-weight: bold;text-align:center;font-size:14px'>CLASE CONTROLADORVIDEO</h3><p style='font-family: "Times New Roman", Times, serif; font-size:14px'>En esta clase se realizará los ajustes para manejar el video recibido y manipularlo.</p>


In [2]:
class ControladorVideo:
    def __init__(self,enlace): 
        self._idvideo = self.reenumerar()
        self.enlacevideo=enlace
        self.yt=YouTube(self.enlacevideo)
        self.nombrevideo=''
        self.titulovideo=self.yt.title
        self.autorvideo=self.yt.author
        self.fechavideo=self.yt.publish_date
        self.duracionvideo=self.yt.length
    """|DESCARGAR VIDEO URL: descarga el video de youtube
       |return: devuelve una ruta absoluta"""
    def descargarVideoURL(self):
        recetasVideos = 'recetasvideos/'
        #aqui creo un nuevo id para el nuevo video
        self._idvideo= self._idvideo+1
        #esta sera el archivo del video y su nuevo nombre
        nombre='receta'+str(self._idvideo)
        #le pedimos al pytube que solo nos descargue el audio y lo descargamos
        t=self.yt.streams.filter(file_extension='mp4').first().download(output_path=recetasVideos,filename=nombre+'.mp4')
        #devolvemos el nombre
        return nombre
    """|PARSEO VIDEO: pasa el video de .mp4 a .wav
       |nombre: es un string que se colocara el nombre del video
       |return: devuelve el nuevo nombre del audio en .wav"""
    def parseoVideo(self,nombre):
        recetasVideos = 'recetasvideos/'
        #tomamos el video en mp4 
        track = mp.VideoFileClip(recetasVideos+nombre+'.mp4')
        #cambiamos el video a .wav
        nombre_wav="{}.wav".format(nombre)
        track.audio.write_audiofile(recetasVideos+nombre_wav)
        track.close()
        return nombre
    """|REENUMERAR: Devuelve cual es el id del siguiente video.
       |primer for: recorre cada carpeta de /recetastextos
       |segundo for: cuenta cada archivo dentro de /recetastextos/* """
    def reenumerar(self):
        contador = 0
        for item in pathlib.Path("./recetastextos/").iterdir():
            if item.is_file():
                contador += 1
            elif item.is_dir():
                for subitem in item.iterdir():
                    if subitem.is_file():                     
                        contador += 1
        return contador
    """|SPEECH TEXT:Transforma el audio a texto
       |nombre: es un string que se colocara el nombre del video
       |return: devuelve un string con el texto devuelto"""
    def speech_text(self,nombre):
        recetasVideos = 'recetasvideos/'
        #instanciamos el recognizer
        r = sr.Recognizer()
        audio = sr.AudioFile(recetasVideos+nombre)
        with audio as source:
            audio_file = r.record(source)
        #transcribimos el audio a texto
        result = r.recognize_google(audio_file, language = 'es-ES')
        return result
        

<h3  style='font-family: "Times New Roman", Times, serif; font-weight: bold;text-align:center;font-size:14px'>CLASE DEPURADOR</h3><p style='font-family: "Times New Roman", Times, serif; font-size:14px'>En esta clase se realizará el proceso de extraccion, transformacion y carga de nuestro programa EATEASER.</p>


In [3]:
#si el video es mayor de 3 minutos no funciona
#si el video es en ingles no funciona
class Depurador:
    def __init__(self): 
        self.rec=RecursosAdicionales()
    """|VIDEO: proceso etl donde extraemos al informacion del video 
       |enlace: es un string que se colocara el enlace del video"""
    def video(self,enlace):
        try:
            #instanciamos el controlador de videos
            cv=ControladorVideo(enlace)
            #paso 1: descargamos el video
            cv.nombrevideo=cv.descargarVideoURL()
            #paso 2: pasamos el video a .wav
            nombre=cv.parseoVideo(cv.nombrevideo)
            #paso 3: pasamos el .wav a texto
            try:                
                num_segm=self.rec.segcionarXsilencios(nombre)
                result=""
                for i in range(num_segm):
                    result=result+str(cv.speech_text("../temp_audios/{}_extracto{}.wav".format(nombre,i+1)))
                    result=result+" "
                #paso 4: escribimos el texto recibido en un txt
                self.rec.eliminacionWav_Audios("temp_audios")
                try:
                    quitarEmojis = dict.fromkeys(range(0x10000, sys.maxunicode + 1), 'NULL')
                    tituloSinEmojis=cv.titulovideo.translate(quitarEmojis)
                    autorSinEmojis=cv.autorvideo.translate(quitarEmojis)
                    resultado=self.rec.escritura(cv.nombrevideo,"Titulo:"+tituloSinEmojis+"\n"+"Autor:"+autorSinEmojis+"\n"+"Fecha Publicacion:"+str(cv.fechavideo)+"\n"+"Entradilla:"+result)
                    self.rec.eliminacionMp4()
                except Exception as e:
                    print(repr(e))
                    print("No se ha podido eliminar los caracteres corruptos el video: "+ cv.nombrevideo + " - "+ cv.titulovideo)
                    #paso 5: eliminamos los mp4
                    self.rec.eliminacionMp4()
                    return resultado   
            except Exception as e:
                print(repr(e))
                print("No se ha podido transcribir el video: "+ cv.nombrevideo + " - "+ cv.titulovideo+" - "+cv.enlacevideo)
                self.rec.eliminacionMp4()
                self.rec.eliminacionWav_Audios("temp_audios")

                return None
        except Exception as e:
            print(repr(e))
            print("No se ha podido descargar el video: "+ cv.nombrevideo + " - "+ cv.titulovideo)
            return None
    def lista(self, enlace):
        playlist_urls = Playlist(enlace)
        for url in playlist_urls:
            self.video(url)
    def transformacion(self):
        print()
    def carga(self):
        print()

In [4]:
#aqui iran lecturas-escrituras-guardar-eliminar cosas en bases de datos
class RecursosAdicionales:
    """|ESCRITURA: escribe textos txt
       |nombre: nombre del 
       |return: devuelve el audio en texto"""
    #yo siento que en vez de cambiar de carpeta los textos...deberiamos eliminar los mp4
    #y si lo mas factible aqui es que guardemos el video por su nombre?
    #creo que no debemos contar los files porque cansan el programa
    
    def escritura(self,nombre,texto):
        recetasTextos = './recetastextos/'
        if not(os.path.exists(recetasTextos)):
            os.mkdir(recetasTextos)
        f = open(recetasTextos+nombre+'.txt', 'w')
        f.write(texto)
        f = open(recetasTextos+nombre+'.txt', "r")
        print(f.read())
        f.close()
    def eliminacionMp4(self):
        recetasVideos = './recetasvideos/'
        py_files = glob.glob(recetasVideos+'*.mp4')
        for py_file in py_files:
            try:
                os.remove(py_file)
            except OSError as e:
                print(f"Error:{ e.strerror}")
                
    def eliminacionWav_Audios(self, path):
        url = './'+path+'/'
        py_files = glob.glob(url+'*.wav')
        for py_file in py_files:
            try:
                os.remove(py_file)
            except OSError as e:
                print(f"Error:{ e.strerror}") 
    
    def segcionarXsilencios(self,audio):
        import numpy as np
        from pydub import AudioSegment as aseg

        audio1=aseg.from_wav("./recetasvideos/"+audio+".wav")
        # this is an array
        samples = audio1.get_array_of_samples()
        segundo=88521
        index=[]
        for i in range(0,len(samples),int(segundo/5)):
            dataSeg = samples[i:int(segundo/5)+i]
            media=np.mean(dataSeg)
            var=np.var(dataSeg)
            if -10<=media<=10 and var<=1900:
                index.append(i)

        borrar=[]
        guardado=0
        for i in range(len(index)-1):
            if index[i+1]<=index[i]+(20*segundo):
                if i==0:
                    tiempo=(index[i])/segundo
                else:
                    tiempo=(index[i+1]-guardado)/segundo
                if tiempo<=120:
                    borrar.append(i)
                else:
                    print("guardados: " + str(index[i]/segundo))
                    guardado=index[i]
            else:
                guardado=index[i]

        final=np.delete(index, borrar, axis=0) 
        print("------------------------------------------------")
        print(final)
        print("------------------------------------------------")
        extractos=[]
        for i in range(len(final)):
            if i==0:
                extractos.append(samples[:final[i]])
            else:
                extractos.append(samples[final[i-1]:final[i]])
        for i in range(len(extractos)):
            nombre=""
            new_sound = audio1._spawn(extractos[i])
            nombre="temp_audios/{}_extracto{}.wav".format(audio,i+1)
            new_sound.export(nombre,format="wav")
        return len(final)

In [5]:
class WebScrap:
    def __init__(self): 
        self.headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    def request(self, url):
        request1 = requests.get(url, headers=self.headers)
        html = request1.content
        soup = BeautifulSoup(html, 'html.parser')
        return soup
    def verificar_alimento(self,alimento):
        soup = self.request( 'https://www.themealdb.com/api/json/v1/1/search.php?s='+alimento)
        print(soup)
        

<h2 style="font-size: 19px;color:#6DA0FF;font-family:Georgia, Times, 'Times New Roman', serif;letter-spacing: 3px;font-weight: normal">3. Main</h2>

In [6]:
#y si tambien vemos si le permitimos al usuario que meta videos?
dep=Depurador()
if __name__ == '__main__':
    #dep.video('https://www.youtube.com/watch?v=6PzQY1E2s2g&list=PLxHmjpcgU5ArC2rY5cpoIcZoVKB_0UHfR&ab_channel=PlatosF%C3%A1cilesconTamara')
    #dep.video('https://www.youtube.com/watch?v=PsqR5M8rdjA&list=LL&index=9&t=4s')
    #dep.video('https://www.youtube.com/watch?v=xfYcM_jHgPY')
    #dep.video('https://www.youtube.com/watch?v=wiCfqc5W-yo')
    #error_nuevo#dep.video('https://www.youtube.com/watch?v=3DnPkf9rP_0')
    #error_nuevo#dep.video('https://www.youtube.com/watch?v=xVsgKMZFCZY')
    #dep.video('https://www.youtube.com/watch?v=rpCe0RPMY94')
    #dep.video('https://www.youtube.com/watch?v=rv4gLMa-FYk')
    #dep.video('https://www.youtube.com/watch?v=VS8zYxBj4r8')
    #dep.video('https://www.youtube.com/watch?v=o99JXrEkZoo')
    #dep.video('https://www.youtube.com/watch?v=lKkg5L23b3M')
    #dep.video('https://www.youtube.com/watch?v=PsqR5M8rdjA&t=14s')
    #dep.video('https://www.youtube.com/watch?v=IvZaAL6qYe0&t=29s')
    #dep.video('https://www.youtube.com/watch?v=SIMQBuuyE9M')
    #dep.video('https://www.youtube.com/watch?v=_YoZfg7R8Hk')
    #dep.video('https://www.youtube.com/watch?v=Zv7KdlOBk7Y')
    #dep.video('https://www.youtube.com/watch?v=mFcN4btaZyI&t=2s')
    #dep.video('https://www.youtube.com/watch?v=sRmmQBBln9Q')
    #dep.video('https://www.youtube.com/watch?v=-QoTJJJfeEE')
    #dep.video('https://www.youtube.com/watch?v=JRY5obPKPzo&list=PLxHmjpcgU5ArC2rY5cpoIcZoVKB_0UHfR&index=5&ab_channel=PlatosF%C3%A1cilesconTamara')
    #dep.video('https://www.youtube.com/watch?v=stFmx7OCy1k&ab_channel=RecetasdeEsbieta')
    #error_videomuylargo#dep.video("https://www.youtube.com/watch?v=qqTqePGIjhc")
    #dep.lista("https://youtube.com/playlist?list=PLQwfLPYiFlOsS9x6zgeZmFRLqDx3poZvw")
    dep.lista("https://www.youtube.com/playlist?list=PLIsSIvqffHZvM2v1QS5Zi0MUL258EKLPq")
    

MoviePy - Writing audio in recetasvideos/receta24.wav


MoviePy - Done.
------------------------------------------------
[ 548824 9276896]
------------------------------------------------
Titulo:Churrasco a la plancha con sorpresa / Carne a la plancha - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-06-03 00:00:00
Entradilla:la gente un poquito dice la plancha una forma de alegrar un vicio a la plancha también un poco rara pero qué buenísimo confía en mí esta noche para saber más así que está pido esta pasta pero me vas a mandar un mensaje puedes hacer la Paulina gracias gracias gracias nunca más vuelvo a desconfiar en voz presta atención TSP entonces qué vas a comer todavía no están las planchas recaliente como si tienes un momento le vas a poner el pollito de lado de la mesa de café mientras está haciendo le pones por arriba y eso no es el tiempo que dejes tu churrasco un poco jugado todo entonces lo estoy dejando un minuto fuerte y luego bajo el fuego medio otro minuto y lo vemos prontito de cada lado cuenta y lo terminamos d

MoviePy - Done.
------------------------------------------------
[  495712  7258640 12162648]
------------------------------------------------
Titulo:Cómo hacer tortitas ¡RÁPIDO!: Tortitas de maíz / Choclo  - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-07-01 00:00:00
Entradilla:vamos a hacer tortitas de coco tortilla de choclo no de coco particularidad que se pueden hacer dulces o saladas quieres una pasta ING agregamos el huevo y pequeñito la mezcla bien bien yo cereales salpimienta y el queso racha si son las dulces en esta parte le pones el azúcar y el queso que se rifa si quieres vas a poner chorrito de aceite en una sartén y no me gusta escuchar más a empezar a poner la mezcla de las tortitas a todo medio a maravisa así se van haciendo las tortitas cuando las ves doraditas de un lado las das vueltas ya y las vas pasando importante hacerlo fuego medio a fuego fuerte se van a quemar a fuego suave se van a acercar las ponemos aquí en una fuentecita en mi caso le tiramo

MoviePy - Done.
guardados: 127.99855401543137
------------------------------------------------
[  318672 11330560 12941624 16960432]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta26 - Receta de Sopa Paraguaya - Paulina Cocina T04 #10 - https://www.youtube.com/watch?v=XMur7aWyCH8
MoviePy - Writing audio in recetasvideos/receta26.wav


MoviePy - Done.
------------------------------------------------
[ 336376 5470536 9666384]
------------------------------------------------
Titulo:Pastel de Verduras (Strata): absolutamente GENIAL- Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-04-15 00:00:00
Entradilla:estoy firmando hacer una receta de verduras que me robó el corazón nunca nunca es fácil de verdura se trata de verduras le van cantar señora y si lo Pokémon y familia sonriendo a la cámara es típico como si fuera una tarta pero como quieras es tonto te van a cantar en la señora ingredientes para una fuente mediana son un paquete de espinaca una cebolla cuatro o cinco tomates secos unos 3 pancitos como los que te voy a mostrar o el equivalente en volumen de los ciegos tenga tres huevos sal pimienta y un chorrito de aceite guarnición para usar como plato único final Cataluña y los tomates secos que los tengo hidratando hace un ratito en aguas tibias siguiente que hacemos es en 1 1 8 vamos a poner un chorrito d

MoviePy - Done.
guardados: 173.39804114277968
------------------------------------------------
[  584232 15349368 15774264]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta27 - Papas a la Crema Gratinadas (patatas) - Paulina Cocina T04 #05 - https://www.youtube.com/watch?v=jst9IhRfHnU
MoviePy - Writing audio in recetasvideos/receta27.wav


MoviePy - Done.
guardados: 200.99772935235706
------------------------------------------------
[  407192 17792520 17863336]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta27 - Pollo a la Mostaza en 8 pasos sencillos - Paulina Cocina - https://www.youtube.com/watch?v=ciSwx4QxKvk
MoviePy - Writing audio in recetasvideos/receta27.wav


MoviePy - Done.
------------------------------------------------
[ 6355736 10197504]
------------------------------------------------
Titulo:Sopa de Calabaza y Jengibre ¡Light! - Paulina Cocina T03 #14
Autor:Paulina Cocina
Fecha Publicacion:2014-09-12 00:00:00
Entradilla:sean bienvenidos al cine una sopa de calabaza frita fácil Purísima ingredientes una calabaza media cebolla una rodaja de jengibre gorda una cucharadita de curry media cucharadita de cúrcuma una cucharada de manteca sal pimienta y aceite le pongo con la cáscara solo le quitó el culito en cuadraditos no importa el tamaño está papá también portada pedacitos tamaño calentando más cerca siempre con un chorrito de aceite para que no sé que me ibas a poner ahí a saltear la cebolla cuando la cebolla esté transparente cita y agregar la papa y la calabaza calabaza y también la manchita depresible saltear buen rato revólver trabajo hasta que esté un poco gracias laskuri hasta arriba más que eso y la pones a hervir 
MoviePy - Writ

MoviePy - Done.
------------------------------------------------
[513416]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta28 - Como cocer pasta (y que quede BIEN!) - Paulina Cocina - https://www.youtube.com/watch?v=rA6AN3RGRFc
MoviePy - Writing audio in recetasvideos/receta28.wav


MoviePy - Done.
------------------------------------------------
[  513416  5913136  9967352 12870808]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta28 - Pescado fácil a la Sal - Paulina Cocina - https://www.youtube.com/watch?v=QtaHG8Sd2SI
MoviePy - Writing audio in recetasvideos/receta28.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Cómo hacer huevos revueltos (¡y que queden GENIALES!) / Recetas con huevo - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-08-28 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta29.wav


MoviePy - Done.
------------------------------------------------
[  655048  5806912 13525856]
------------------------------------------------
Titulo:Filetes rusos paso a paso / Recetas con carne picada o molida - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-08-26 00:00:00
Entradilla:Lenin Trotsky Dostoievski Tolstói fin de rusos para todos chicos filetes rusos la milanesa de Nadia Comaneci entre hamburguesa y noviembre el mes posterior a la Revolución de Octubre de rusos todo el mundo ni sabemos ya rosa pero si son filetes vosotros tío raro pero bueno no solo uso muchos son buenos así que probarlas filetes rusos precio balalaika que lo primero que hacemos es rayar la cebosa bien pasadita porque rosada y no picada podrás olvidar a Marta entonces tenemos aquí en un bol nuestra carne picada ancianos a mezclar con la papá la papá simplemente es minutos de papá cocida y bien aplastar y casi nadie solo vamos a mezclar nuestra cebollita Ratjada no mezclar bien vamos a condiment

MoviePy - Done.
------------------------------------------------
[  601936  4284368 10764032]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta30 - Papas chips ¡SIN aceite! / Recetas con papas- Paulina Cocina - https://www.youtube.com/watch?v=75qssKMIgm4
MoviePy - Writing audio in recetasvideos/receta30.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Pollo a la cacerola ¡FÁCIL! / Recetas con pechuga de pollo - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-08-27 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta31.wav


MoviePy - Done.
------------------------------------------------
[17704]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta31 - Puré de coliflor y papas / Recetas de verduras para NIÑOS - Paulina Cocina - https://www.youtube.com/watch?v=7fhtGPRZyQ8
MoviePy - Writing audio in recetasvideos/receta31.wav


MoviePy - Done.
------------------------------------------------
[ 655048 7276344]
------------------------------------------------
Titulo:Receta gazpacho andaluz, con Anabel Cherubito - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-09-02 00:00:00
Entradilla:la renuncia la máquina una vez más tiempo gazpacho Ana chiringuito invitada hermosa buena Oz igual vamos a recordar este día para siempre como el día en que se nos perdió en proteínas y el pepino te quedan la verdulería en el tomate el pepino con la piel el ají y el ajo con un poquito de agua 
MoviePy - Writing audio in recetasvideos/receta32.wav


MoviePy - Done.
------------------------------------------------
[  442600  5204976 14340240]
------------------------------------------------
Titulo:CÓMO HACER PATACONES ¡ECONÓMICOS! RECETA COLOMBIANA (TOSTONES)
Autor:Paulina Cocina
Fecha Publicacion:2015-09-09 00:00:00
Entradilla:eso no es una banana es un plátano macho te va a quedar la buscaba como lengua de gato Anthos A7 cocina típico de la cocina latinoamericana típico de la cocina caribeña y hay una forma que es fantástica para probarlo por primera vez que son los patacones te voy a dar la receta es super simple y me está doliendo años de Venezuela de Colombia se están riendo de mí acá en Argentina no sabemos ni lo que conozca tacones muy pedido esto por esto porque me encanta eso que lo primero no es fácil pelar un plátano macho no se pela así con una gana hacemos corta si íbamos haciendo cortes profundos cortes toda la cáscara así con el coche eso y luego lo vamos sacando de esta manera así se pela un plátano macho la cáscara

MoviePy - Done.
------------------------------------------------
[0]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta33 - Empanadas de jamón y queso: un TRUCO / Recetas argentinas- Paulina Cocina - https://www.youtube.com/watch?v=OfFv4YDgK3Y
MoviePy - Writing audio in recetasvideos/receta33.wav


MoviePy - Done.
------------------------------------------------
[  761272  5895432 10675512 15384776 21669696 25299016 27476608]
------------------------------------------------
Titulo:Bife de chorizo a la plancha: 10 TRUCOS / Recetas de carne - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-09-30 00:00:00
Entradilla:necesito pollito hacer un bife a la plancha te va a venir genial pero si sabes hacerlo porque tiene su ciencia se dice la plancha el Wi-Fi por excelencia chorizo que me encanta que sea así como así que te voy a pasar Raquel estaba la visa se convierta en el 10 minutos por lo menos saber la intensidad del calor y a poco vas a ir entendiendo cuál es la intensidad que no te crezca la práctica la práctica la plancha está bien caliente acortar está Gracita que tiene acá pedacito la ficha que te lo pasas por arriba la plancha esa Gracita va a ser que él dice que iba a ser que se cuesta más falso que le ponemos dices tú sales antes la carne se puede desalar si la est

MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Salsa de pollo para pastas / Salsas para pastas - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-10-09 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta35.wav


MoviePy - Done.
------------------------------------------------
[  247856 18748536 21156280]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta35 - Pan casero de lino: SIN harina, sin gluten ¡y adelgaza!. Una receta de pan para celíacos genial. - https://www.youtube.com/watch?v=Jvjfdj5afs0
MoviePy - Writing audio in recetasvideos/receta35.wav


MoviePy - Done.
------------------------------------------------
[  601936  6886856 15969008 18783944]
------------------------------------------------
Titulo:Pollo a la sal EN 2 PASOS sencillos o cómo hacer pollo al horno SÚPER fácil, queda jugoso!!!
Autor:Paulina Cocina
Fecha Publicacion:2015-10-14 00:00:00
Entradilla:pon mi nombre qué tal chicos hola salva para pegar dentadura y con tirar algo al horno que pesa mucho la sal vosotras al esposo te queda súper cub osito nada más que incluyen trocante por afuera fantástico y directo al horno con eso que te voy a dar que quedar mucho mejor pero sino que vamos a hacer es una mezcla de manteca que este tiempo más con ajo sal pimienta y orégano muy bien ya tenemos el pozo un poquito de Campoamor y lo que vamos a hacer es con la mano que vamos desprendiendo Gabriel de por allí dentro con la misma mano vamos a meter toda esta amanecer carta hasta donde pueda lo que vamos a hacer es agarrar una linda fuente para horno hola estáis cuántos Altam

MoviePy - Done.
------------------------------------------------
[ 1628768  3700136 13685192]
------------------------------------------------
Titulo:Carpaccio de calabacín / Ensaladas frías - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-11-11 00:00:00
Entradilla:ensalada de verano cuéntame alguna idea para pasarme también me sirves carpaccio de calabacín teléfono de decir carpaccio no porta nada ensalada está buenísima así que nombre para esto a los cocineros de verdad queremos comer mira cómo está la cosa para cortar con una mandolina pesadísimo que le podríamos a una hija mandolina del alguna oportunidad muy bonito nombre lo vas a coger en una fuente o plato así en lo que pasó la mía se dice en la cabecita y le vamos a poner arriba rachaduras de limón en medio que ponemos también sale porque somos muy pimienta negra y vas a poner bastante limón eso sí como está lo vamos a llevar a la heladera 1 chicos hasta que tengan la otra comida minutos un ratito verdadera no sacan

MoviePy - Done.
------------------------------------------------
[389488]
------------------------------------------------
Titulo:Pasta de verano (¡todo en la licuadora!) / Recetas de verano - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-11-18 00:00:00
Entradilla:cuadro ahora 
MoviePy - Writing audio in recetasvideos/receta38.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Huevos Pericos: Recetas para desayunos ¡RIQUÍSIMOS! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-11-20 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta39.wav


MoviePy - Done.
------------------------------------------------
[300968]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta39 - Cómo hacer salchichas caseras ¡SIN máquina! - Paulina Cocina - https://www.youtube.com/watch?v=BaQ3FSH1Xsk
MoviePy - Writing audio in recetasvideos/receta39.wav


MoviePy - Done.
------------------------------------------------
[318672]
------------------------------------------------
Titulo:Cheesecake sin horno en 5 pasos ¡fácil y rápido! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-12-02 00:00:00
Entradilla:qué chiste 
MoviePy - Writing audio in recetasvideos/receta40.wav


MoviePy - Done.
------------------------------------------------
[2921160]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta40 - Ensalada fresca de rúcula / Recetas de ensaladas - Paulina Cocina - https://www.youtube.com/watch?v=RXVh_smMC1c
MoviePy - Writing audio in recetasvideos/receta40.wav


MoviePy - Done.
------------------------------------------------
[371784]
------------------------------------------------
Titulo:Receta de VITEL TONÉ para navidad: Como hacer vitel toné muy fácil - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-12-16 00:00:00
Entradilla:estoy en el equipo Navidad 
MoviePy - Writing audio in recetasvideos/receta41.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Duraznos en almíbar en 2 simples pasos - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2015-12-18 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta42.wav


MoviePy - Done.
------------------------------------------------
[3700136]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta42 - Helado de frutillas falso, casero, sano y riquísim - https://www.youtube.com/watch?v=DQcjyMtmbq4
MoviePy - Writing audio in recetasvideos/receta42.wav


MoviePy - Done.
------------------------------------------------
[336376]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta42 - TORTA DE CHOCOLATE FÁCIL DE 2 INGREDIENTES (¡FUNCIONA!) / TORTA CON HELADO - https://www.youtube.com/watch?v=wpVSY71PoBM
MoviePy - Writing audio in recetasvideos/receta42.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Café frappé ¡en 1 minuto! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-02-19 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta43.wav


MoviePy - Done.
------------------------------------------------
[247856]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta43 - RECETA DE HELADO DE MC DONALDS CASERO ¡ES MUY FÁCIL! (Helado casero fácil para Sundae o Mc Flurry) - https://www.youtube.com/watch?v=qU-npk3gf7g
MoviePy - Writing audio in recetasvideos/receta43.wav


MoviePy - Done.
------------------------------------------------
[265560]
------------------------------------------------
Titulo:Receta de JUGOS concentrados caseros ¡ricos!- Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-03-02 00:00:00
Entradilla:tengo una 
MoviePy - Writing audio in recetasvideos/receta44.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Hacer estas PAPAS ESPIRAL es fácil / Recetas de papas - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-03-18 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta45.wav


MoviePy - Done.
------------------------------------------------
[212448]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta45 - Pastel de ATÚN ¡en la licuadora! / Recetas con atún - Paulina Cocina - https://www.youtube.com/watch?v=Vgw4u4yVBNY
MoviePy - Writing audio in recetasvideos/receta45.wav


MoviePy - Done.
guardados: 242.39726166672315
------------------------------------------------
[  407192 21457248 21598880]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta45 - Masa para pizza SIN horno y SIN levadura: receta de pizza fácil y rápida, - https://www.youtube.com/watch?v=QYjkWjJAB8I
MoviePy - Writing audio in recetasvideos/receta45.wav


MoviePy - Done.
guardados: 420.1952531037833
------------------------------------------------
[  230152 37196104 37231512]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta45 - Pollo frito o al horno SÚPER crocante / Recetas de pollo - Paulina Cocina - https://www.youtube.com/watch?v=XHf45druNe4
MoviePy - Writing audio in recetasvideos/receta45.wav


MoviePy - Done.
------------------------------------------------
[265560]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta45 - TORTA DE MANZANA invertida SIN horno (Tarta de manzana en sartén) - https://www.youtube.com/watch?v=g7cVPgseIVI
MoviePy - Writing audio in recetasvideos/receta45.wav


MoviePy - Done.
------------------------------------------------
[336376]
------------------------------------------------
Titulo:Cómo hacer PANQUEQUES y panqueques con dulce de leche: 6 TRUCOS de la masa para panqueques
Autor:Paulina Cocina
Fecha Publicacion:2016-04-27 00:00:00
Entradilla:apaga y vámonos 
MoviePy - Writing audio in recetasvideos/receta46.wav


MoviePy - Done.
------------------------------------------------
[  354080 24626264]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta46 - Hígado encebollado / Recetas económicas - Paulina Cocina - https://www.youtube.com/watch?v=4GvfMEBN0EM
MoviePy - Writing audio in recetasvideos/receta46.wav


MoviePy - Done.
------------------------------------------------
[265560]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta46 - Pasta GRATINADA con queso y jamón muy FÁCIL!  / Recetas de pastas - Paulina Cocina - https://www.youtube.com/watch?v=0v2Gf3q52Og
MoviePy - Writing audio in recetasvideos/receta46.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Tortitas de PAPA... ¡con restos de puré! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-06-10 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta47.wav


MoviePy - Done.
------------------------------------------------
[283264]
------------------------------------------------
Titulo:Barritas de cereal caseras MUY fáciles: 2 ingredientes, sin horno!!! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-06-15 00:00:00
Entradilla:tattoo 
MoviePy - Writing audio in recetasvideos/receta48.wav


MoviePy - Done.
------------------------------------------------
[247856]
------------------------------------------------
Titulo:MASA para tarta salada 9-9-9 ¡GENIAL y sin manteca! - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-06-29 00:00:00
Entradilla:Monster cartoon 
MoviePy - Writing audio in recetasvideos/receta49.wav


MoviePy - Done.
------------------------------------------------
[194744]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta49 - TARTA DE VERDURA HERMOSA! (Pastel de verduras con "rosas") - https://www.youtube.com/watch?v=HzYXxz6PNww
MoviePy - Writing audio in recetasvideos/receta49.wav


MoviePy - Done.
guardados: 846.39043842704
------------------------------------------------
[74923328 75100368]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta49 - POLLO A LA CREMA en 5 minutos / Recetas de microondas (Y GRAN PIFIE en VIVO!!!) - Paulina Cocina - https://www.youtube.com/watch?v=Mz2oTS9PLBY
MoviePy - Writing audio in recetasvideos/receta49.wav


MoviePy - Done.
guardados: 260.5970560657923
------------------------------------------------
[   70816  5382016  9046744 23068312 23103720 31920312 38045896]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta49 - Tarta de brocoli / Recetas de tartas saladas - Paulina Cocina - https://www.youtube.com/watch?v=D_kIH6zExBg
MoviePy - Writing audio in recetasvideos/receta49.wav


MoviePy - Done.
------------------------------------------------
[283264]
------------------------------------------------
Titulo:PIZZETAS de pan lactal: receta para que cocinen los niños - Especial día del niño
Autor:Paulina Cocina
Fecha Publicacion:2016-08-17 00:00:00
Entradilla:vídeo me lo pidió el medio 
MoviePy - Writing audio in recetasvideos/receta50.wav


MoviePy - Done.
------------------------------------------------
[106224]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta50 - Pasta al vino tinto ¡SORPRENDENTE! / Pasta fácil y rápido - Paulina Cocina - https://www.youtube.com/watch?v=YkxN-8R-fUg
MoviePy - Writing audio in recetasvideos/receta50.wav


MoviePy - Done.
guardados: 328.9962833677884
------------------------------------------------
[29123080 29140784 39426808 46685448]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta50 - Pasta Alfredo con pollo SÚPER RÁPIDA / Pastas fáciles - Paulina Cocina - https://www.youtube.com/watch?v=TWPkGsCNN1c
MoviePy - Writing audio in recetasvideos/receta50.wav


MoviePy - Done.
guardados: 129.39853819997515
guardados: 501.79433128862075
------------------------------------------------
[  159336 11454488 14074680 44419336 46844784]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta50 - Pasta ONE POT mediterránea / Recetas de pastas - Paulina Cocina - https://www.youtube.com/watch?v=P2FpmpukWBU
MoviePy - Writing audio in recetasvideos/receta50.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Receta de hamburguesas RELLENAS / 30 minutos - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-10-07 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta51.wav


MoviePy - Done.
------------------------------------------------
[21687400 31654752 36151568 40701496 47216568 53767048]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta51 - Pastel de espinacas en 30 MIN. / Recetas de verduras - Paulina Cocina - https://www.youtube.com/watch?v=VL7Ru24dVXs
MoviePy - Writing audio in recetasvideos/receta51.wav


MoviePy - Done.
------------------------------------------------
[]
------------------------------------------------
Titulo:Receta VITEL TONÉ de pollo / Recetas para navidad - Paulina Cocina
Autor:Paulina Cocina
Fecha Publicacion:2016-12-02 00:00:00
Entradilla:
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 346.39608680426113
------------------------------------------------
[       0 30663328 30716440]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - Entradas para navidad DE ÚLTIMO MOMENTO / Recetas para fiestas - Paulina Cocina - https://www.youtube.com/watch?v=RtF7k9uDHTI
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 656.3925848103839
------------------------------------------------
[       0 58104528 58246160 62725272]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - Cómo hacer GERMINADOS  // Germinar lentejas y otras semillas - Paulina Cocina - https://www.youtube.com/watch?v=xTsf5TqCzKo
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 644.7927158527355
------------------------------------------------
[       0 57077696 57130808]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - Viandas SALUDABLES para niños ft. Anna recetas fáciles y Mamá Sana - Paulina Cocina - https://www.youtube.com/watch?v=DkZi70xs4Y8
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 594.1932874685103
------------------------------------------------
[       0 52598584 52917256]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - Cómo hacer AREPAS y arepas rellenas ¡LAS AUTÉNTICAS! Receta para celiacos (receta sin gluten) - https://www.youtube.com/watch?v=Gk0AtNJzJ0Y
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 793.9910303769727
------------------------------------------------
[       0 70284880 70337992]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - Cómo hacer tortilla de papas: ASÍ LA HAGO YO (tortilla española) - https://www.youtube.com/watch?v=zfdzfDGc-1k
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 841.9904881327594
------------------------------------------------
[74533840 74746288]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - Cómo hacer tarta de atún PASO A PASO (Receta tipo empanada gallega) - https://www.youtube.com/watch?v=9-vwUyyehNs
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 781.5911704567278
------------------------------------------------
[       0 69187232 69328864]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - CÓMO HACER GUISO DE LENTEJAS (CON CARNE) - https://www.youtube.com/watch?v=qRHymy7Ue4E
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 453.794873532834
------------------------------------------------
[  832088 40170376 40258896 47358200]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - BIFES A LA CRIOLLA: cena rápida, fácil... ¡y sin ensuciar!!! - https://www.youtube.com/watch?v=989XjP0mSyw
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 754.3914777284486
------------------------------------------------
[66779488 66832600]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - BUÑUELOS DE VERDURAS FRITOS Y AL HORNO - de espinaca y de zanahoria - https://www.youtube.com/watch?v=vU5-FtXKxCg
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 592.9933010246157
------------------------------------------------
[52492360 52917256]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - BOMBAS DE PAPA CON 6 RELLENOS - ¡Una locura! - https://www.youtube.com/watch?v=NwJzb4SXosA
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 832.9905898035495
------------------------------------------------
[73737160 73790272]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - 3 TARTAS DE VERDURAS INCREÍBLES - ¡la segunda es riquísima! - https://www.youtube.com/watch?v=Pk9qaWHzJn0
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 723.9918211497836
------------------------------------------------
[64088480 64265520]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - SOPA DE CALABAZA: 3 OPCIONES ft. DALMA MARADONA - https://www.youtube.com/watch?v=NEuLgdudHIE
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 534.9939562363733
------------------------------------------------
[47358200 47464424]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - ZAPALLITOS RELLENOS - Súper sanos y ricos - https://www.youtube.com/watch?v=T3jbUQT_z1Q
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 1261.5857480145953
------------------------------------------------
[   371784 111676832 111783056]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - COCINÁ 1 DÍA PARA COMER SALUDABLE TODA LA SEMANA - El #1000prep VUELACABEZAS🤯 - https://www.youtube.com/watch?v=8QHjLvfg8aw
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
------------------------------------------------
[56829840]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - 21 ENSALADAS que NO SON lechuga y tomate: la BIBLIA de la ensalada - Paulina Tirapostas E00 - https://www.youtube.com/watch?v=G3JfV4BCuwg
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 164.998136035517
------------------------------------------------
[       0 14605800 15154624]
------------------------------------------------
UnknownValueError()
No se ha podido transcribir el video: receta52 - POSEIDÓN | Destripando la Historia | Canción - https://www.youtube.com/watch?v=2-VTUyI3w7U
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
------------------------------------------------
[55926936]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - 7 IDEAS para HALLOWEEN 🎃 - 7 Comidas de halloween que funcionan, 1 que NO funciona - https://www.youtube.com/watch?v=wEgl6I1If3M
MoviePy - Writing audio in recetasvideos/receta52.wav


MoviePy - Done.
guardados: 763.5913737983077
------------------------------------------------
[ 6656704  9914240 22041480 32203576 35726672 39426808 67593872 67629280]
------------------------------------------------
RequestError('recognition request failed: Bad Request')
No se ha podido transcribir el video: receta52 - LA MEJOR TARTA DE BERENJENAS QUE PROBARON 🍆- Receta de mi tía Alicia - https://www.youtube.com/watch?v=riVDxV-sXP0
